// Key & Token
export const GET_TOKEN = {
    SUCCESS: "GET_TOKEN_SUCCESS",
}

export const CLEAR_TOKEN = {
    SUCCESS: "CLEAR_TOKEN_SUCCESS"
}

export const GET_KEY = {
    SUCCESS: "GET_KEY_SUCCESS",
}

export const CLEAR_KEY = {
    SUCCESS: "CLEAR_KEY_SUCCESS",
}

// Login-Logout
export const LOGIN_USER = {
    SUCCESS: "LOGIN_USER_SUCCESS",
    FAILURE: "LOGIN_USER_FAILURE",
    REQUEST: "LOGIN_USER_REQUEST",
}

export const LOGOUT_USER = {
    SUCCESS: "LOGOUT_USER_SUCCESS",
}

// Vault Actions
export const FETCH_VAULTS = {
    SUCCESS: "FETCH_VAULTS_SUCCESS",
    FAILURE: "FETCH_VAULTS_FAILURE",
    REQUEST: "FETCH_VAULTS_REQUEST",
}

export const ADD_VAULT = {
    SUCCESS: "ADD_VAULT_SUCCESS",
    FAILURE: "ADD_VAULT_FAILURE",
    REQUEST: "ADD_VAULT_REQUEST",
}

export const EDIT_VAULT = {
    SUCCESS: "EDIT_VAULT_SUCCESS",
    FAILURE: "EDIT_VAULT_FAILURE",
    REQUEST: "EDIT_VAULT_REQUEST",
}

export const DELETE_VAULT = {
    SUCCESS: "DELETE_VAULT_SUCCESS",
    FAILURE: "DELETE_VAULT_FAILURE",
    REQUEST: "DELETE_VAULT_REQUEST",
}

export const CLEAR_VAULTS = {
    SUCCESS: "CLEAR_VAULTS_SUCCESS",
}

// Folder Actions
export const FETCH_FOLDERS = {
    SUCCESS: "FETCH_FOLDERS_SUCCESS",
    FAILURE: "FETCH_FOLDERS_FAILURE",
    REQUEST: "FETCH_FOLDERS_REQUEST",
}

export const ADD_FOLDER = {
    SUCCESS: "ADD_FOLDER_SUCCESS",
    FAILURE: "ADD_FOLDER_FAILURE",
    REQUEST: "ADD_FOLDER_REQUEST",
}

export const EDIT_FOLDER = {
    SUCCESS: "EDIT_FOLDER_SUCCESS",
    FAILURE: "EDIT_FOLDER_FAILURE",
    REQUEST: "EDIT_FOLDER_REQUEST",
}

export const DELETE_FOLDER = {
    SUCCESS: "DELETE_FOLDER_SUCCESS",
    FAILURE: "DELETE_FOLDER_FAILURE",
    REQUEST: "DELETE_FOLDER_REQUEST",
}

export const CLEAR_FOLDERS = {
    SUCCESS: "CLEAR_FOLDERS_SUCCESS",
}

// User Actions
export const FETCH_USER = {
    SUCCESS: "FETCH_USER_SUCCESS",
    FAILURE: "FETCH_USER_FAILURE",
    REQUEST: "FETCH_USER_REQUEST",
}

export const ADD_USER = {
    SUCCESS: "ADD_USER_SUCCESS",
    FAILURE: "ADD_USER_FAILURE",
    REQUEST: "ADD_USER_REQUEST",
}

export const EDIT_USER = {
    SUCCESS: "EDIT_USER_SUCCESS",
    FAILURE: "EDIT_USER_FAILURE",
    REQUEST: "EDIT_USER_REQUEST",
}

export const DELETE_USER = {
    SUCCESS: "DELETE_USER_SUCCESS",
    FAILURE: "DELETE_USER_FAILURE",
    REQUEST: "DELETE_USER_REQUEST",
}

export const CLEAR_USER = {
    SUCCESS: "CLEAR_USER_SUCCESS",
}

export const REQUEST = {
    DISPLAY: "REQUEST_DISPLAY",
    CLEAR: "REQUEST_CLEAR"
}